# MySQL Database
version: '3.4'
services:
  mysql:
   container_name: temp-mysql
   image: mysql:8.0
   command: --default-authentication-plugin=mysql_native_password
   environment:
    MYSQL_DATABASE: root
    MYSQL_ROOT_PASSWORD: devonly
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3303:3306"
   restart: always